name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -r ./* $USER@$HOST:/path/to/your/app  # Замените на путь к вашему приложению на сервере
          ssh -i key.pem $USER@$HOST "cd /path/to/your/app && source venv/bin/activate && gunicorn app:app --bind 0.0.0.0:8000 -D"  # Замените на вашу команду для запуска приложения
